@startuml
'https://plantuml.com/sequence-diagram

title Attaque du joueur

participant "main" as MAIN
participant "laby : Labyrinthe" as L
participant "pj : Joueur" as J

participant "epee : Epee" as E
participant "monstre : Monstre" as M


MAIN -> L : deplacerPerso(DROITE)
alt Un monstre se trouve sur la prochaine case
    L -> J : attaquer(monstre)
    alt Le joueur possède une épée
         J -> E : faireDegats(monstre)
         E -> M : perdrePv(20)
         M --> E
         E --> J
    else Le joueur se bat aux poings
        J-> M : perdrePv(2)
        M --> J
    end
end

J-->L

L --> MAIN






@enduml