@startuml
'https://plantuml.com/sequence-diagram

title Récuperation des cases voisines

participant "main" as M
participant "pj : Joueur" as J
participant "laby : Labyrinthe" as L
participant "suivante : int[]" as S
participant "casesVoisines : List<Integer[][]>" as CS

M -> J : recupCasesVoisines(laby3)
activate J

J -> L : getSuivant(5,3, HAUT)
activate L
L -> S : get(0)
activate S
S -> L : 5
deactivate S
L -> S : get(1)
activate S
S -> L : 2
deactivate S
L --> J : 5,2
deactivate L

J -> CS : add(5,2)
activate CS
CS --> J
deactivate CS


J -> L : getSuivant(5,3, BAS)
activate L
L -> S : get(0)
activate S
S -> L : 5
deactivate S
L -> S : get(1)
activate S
S -> L : 4
deactivate S
L --> J : 5,4
deactivate L

J -> CS : add(5,4)
activate CS
CS --> J
deactivate CS

J -> L : getSuivant(5,3, GAUCHE)
activate L
L -> S : get(0)
activate S
S -> L : 4
deactivate S
L -> S : get(1)
activate S
S -> L : 3
deactivate S
L --> J : add(4,3)
deactivate L

J -> CS : add(4,3)
activate CS
CS --> J
deactivate CS

J -> L : getSuivant(5,3, HAUT)
activate L
L -> S : get(0)
activate S
S -> L : 6
deactivate S
L -> S : get(1)
activate S
S -> L : 3
deactivate S
L --> J : 6,3
deactivate L

J -> CS : add(6,3)
activate CS
CS --> J
deactivate CS

J --> M : CasesVoisines
deactivate J

@enduml