@startuml
'https://plantuml.com/sequence-diagram

title Le personnage se déplace sur l'amulette avec un inventaire plein
participant "main" as MAIN
participant "labyrinthe : Labyrinthe" as L
participant "amulette : Amulette" as A
participant "pj : Perso" as P



MAIN -> L : deplacerPerso(DROITE)
activate L
L --> MAIN
deactivate L



MAIN -> L : deplacerPerso(HAUT)
activate L



L -> A : getAmulette()
activate A
A --> L : 1 , 5
deactivate A


L -> P : getPj()
activate P
P --> L: 1 , 5
deactivate P


L ->P : recupererObjet(amulette)
activate P

P -> P : inventairePlein()
activate P

P --> P : true
deactivate P

P --> L
deactivate P


L --> MAIN
deactivate L


@enduml