@startuml
'https://plantuml.com/sequence-diagram

participant "main" as MAIN
participant "dessinLaby : LabyDessin" as LD
participant "labyrinthe : Labyrinthe" as L
participant "sortie : Sortie" as S

activate LD
LD -> L : getAmulette()
activate L
L --> LD : amulette
deactivate L
LD -> S : getX()
activate S
S --> LD : 8
deactivate S
LD -> S : getY()
activate S
S --> LD : 1
deactivate S
LD -> LD : dessinerSortie()
activate LD
LD --> LD
deactivate LD
LD --> MAIN


@enduml